# Generated by Django 6.0.5 on 2026-05-15 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название инструмента')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в сутки')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Залог')),
                ('image', models.ImageField(upload_to='tools/', verbose_name='Фото инструмента')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно сейчас')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория')),
            ],
        ),
    ]
