# Generated by Django 6.0.5 on 2026-05-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='price_per_day',
            field=models.CharField(max_length=50, verbose_name='Цена в сутки'),
        ),
    ]
