# Generated by Django 6.0.5 on 2026-05-15 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_tool_price_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=100, verbose_name='Размер/Диаметр (например, 102 мм)')),
                ('price', models.CharField(max_length=50, verbose_name='Цена для этого размера')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.tool', verbose_name='Инструмент')),
            ],
            options={
                'verbose_name': 'Вариант размера',
                'verbose_name_plural': 'Варианты размеров',
            },
        ),
    ]
