# Generated by Django 6.0.5 on 2026-05-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_toolvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolvariant',
            name='variant_image',
            field=models.ImageField(blank=True, null=True, upload_to='variants/', verbose_name='Фото этого размера'),
        ),
        migrations.AlterField(
            model_name='toolvariant',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='toolvariant',
            name='size_name',
            field=models.CharField(max_length=100, verbose_name='Размер/Диаметр'),
        ),
    ]
