# Generated by Django 6.0.5 on 2026-05-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_toolvariant_variant_image_alter_toolvariant_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
    ]
