# Generated by Django 6.0.5 on 2026-05-18 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_toolvariant_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolvariant',
            name='quantity',
        ),
        migrations.CreateModel(
            name='ToolQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='catalog.tool')),
            ],
            options={
                'verbose_name': 'Количество',
                'verbose_name_plural': 'КОЛИЧЕСТВО',
            },
        ),
    ]
