# Generated by Django 6.0.5 on 2026-05-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_toolvariant_quantity_toolquantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolquantity',
            options={'verbose_name': 'Тариф от количества', 'verbose_name_plural': 'ЦЕНА ОТ КОЛИЧЕСТВА'},
        ),
        migrations.RemoveField(
            model_name='toolquantity',
            name='count',
        ),
        migrations.AddField(
            model_name='toolquantity',
            name='count_from',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во от (шт)'),
        ),
        migrations.AddField(
            model_name='toolquantity',
            name='count_to',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Кол-во до (шт)'),
        ),
        migrations.AddField(
            model_name='toolquantity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена за этот период (сом)'),
        ),
    ]
