# Generated by Django 6.0.5 on 2026-05-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_toolquantity_options_remove_toolquantity_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolquantity',
            options={'verbose_name': 'Количество', 'verbose_name_plural': 'КОЛИЧЕСТВО'},
        ),
        migrations.RemoveField(
            model_name='toolquantity',
            name='count_from',
        ),
        migrations.RemoveField(
            model_name='toolquantity',
            name='count_to',
        ),
        migrations.RemoveField(
            model_name='toolquantity',
            name='price',
        ),
        migrations.AddField(
            model_name='toolquantity',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
