# Generated by Django 6.0.5 on 2026-05-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_toolquantity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='quantity_price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена от количества (например: 1-4 шт — 300 сом)'),
        ),
    ]
