# Generated by Django 6.0.5 on 2026-05-19 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_tool_quantity_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Все товары (Инструменты)'},
        ),
        migrations.AlterModelOptions(
            name='toolimage',
            options={'verbose_name': 'Дополнительное фото', 'verbose_name_plural': 'ГАЛЕРЕЯ ФОТОГРАФИЙ'},
        ),
        migrations.AlterModelOptions(
            name='toolquantity',
            options={'verbose_name': 'Количество', 'verbose_name_plural': 'КОЛИЧЕСТВО ТОВАРА'},
        ),
        migrations.AlterModelOptions(
            name='toolvariant',
            options={'verbose_name': 'Вариант размера', 'verbose_name_plural': 'ВАРИАНТЫ ФИЗИЧЕСКИХ РАЗМЕРОВ'},
        ),
        migrations.RemoveField(
            model_name='tool',
            name='quantity_price',
        ),
        migrations.RemoveField(
            model_name='toolvariant',
            name='price',
        ),
        migrations.AddField(
            model_name='toolvariant',
            name='price_modifier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ЦЕНА ЗА ЭТОТ РАЗМЕР'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название подкатегории'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(upload_to='tools/', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='price_per_day',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цена в сутки (базовая)'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название товара/инструмента'),
        ),
        migrations.AlterField(
            model_name='toolimage',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.tool', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='toolquantity',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='catalog.tool', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='toolvariant',
            name='size_name',
            field=models.CharField(max_length=100, verbose_name='РАЗМЕР / ДИАМЕТР'),
        ),
        migrations.AlterField(
            model_name='toolvariant',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.tool', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='toolvariant',
            name='variant_image',
            field=models.ImageField(blank=True, null=True, upload_to='variants/', verbose_name='ФОТО ЭТОГО РАЗМЕРА'),
        ),
        migrations.CreateModel(
            name='RentalTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.CharField(max_length=100, verbose_name='СРОК АРЕНДЫ (Час/Сутки/День)')),
                ('price', models.CharField(max_length=100, verbose_name='ЦЕНА ЗА СРОК')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='catalog.tool', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Тариф аренды',
                'verbose_name_plural': 'ТАРИФЫ И СРОКИ АРЕНДЫ',
            },
        ),
    ]
