# Generated by Django 6.0.5 on 2026-05-22 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_tool_options_alter_toolimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('total_price', models.PositiveIntegerField(verbose_name='Итоговая сумма (сом)')),
                ('status', models.CharField(choices=[('new', 'Новый (Ожидает подтверждения)'), ('paid', 'Оплачен картой Visa'), ('active', 'В прокате (Инструмент выдан)'), ('completed', 'Завершен (Инструмент вернули)'), ('canceled', 'Отменен')], default='new', max_length=20, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': '🔒 ЗАКАЗЫ КЛИЕНТОВ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='toolvariant',
            name='price_modifier',
        ),
        migrations.AddField(
            model_name='toolvariant',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='ЦЕНА ЗА ЭТОТ РАЗМЕР'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название инструмента')),
                ('size', models.CharField(max_length=100, verbose_name='Вариант/Срок')),
                ('price', models.PositiveIntegerField(verbose_name='Цена (сом)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
    ]
